### ISSUE TITLE
Handle schemas with top level definitions AND complex schemas

### ISSUE THREAD

**Issue by charjr** [membrane-php/membrane-core#179]
Related to #180 and will likely be fixed with the same change.

Currently it is assumed that if any `xOf` is present, then the top level schema is empty.

This may not always be the case, currently we would not handle a schema like this:

```yaml
schema:
  type: string,
  allOf:
    ...
```

Membrane would see the `allOf` and ignore the top level schema, treating it like this:

```yaml
schema:
  allOf:
    ...
```
