### ISSUE TITLE
Handle schemas with multiple complex schemas

### ISSUE THREAD

**Issue by charjr** [membrane-php/membrane-core#180]
Related to #179 and will likely be fixed with the same change.

Currently it is assumed that if any `xOf` is present, you wont also have `yOf` or `zOf`.

This may not always be the case, currently we would not handle a schema like this:

```yaml
schema:
  allOf:
    ...
  anyOf:
    ...
  oneOf:
    ...
```

Membrane would see the `allOf` and ignore anything else:

```yaml
schema:
  allOf:
    ...
```
